import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#444749",
        "outline": "#74777e",
        "on-tertiary-fixed": "#191c1e",
        "on-background": "#111c2d",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b2c7ef",
        "surface": "#f9f9ff",
        "on-secondary-container": "#501600",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b2c7ef",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "on-tertiary-container": "#878a8c",
        "inverse-on-surface": "#ecf1ff",
        "secondary-container": "#fd5900",
        "surface-bright": "#f9f9ff",
        "tertiary-container": "#202325",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#802900",
        "tertiary": "#0a0d0f",
        "surface-tint": "#4a5f81",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbcf",
        "secondary-fixed-dim": "#ffb59a",
        "on-secondary-fixed": "#380d00",
        "surface-variant": "#d8e3fb",
        "surface-dim": "#cfdaf2",
        "surface-container-highest": "#d8e3fb",
        "surface-container": "#e7eeff",
        "on-surface": "#111c2d",
        "secondary": "#a83900",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary-container": "#768baf",
        "inverse-surface": "#263143",
        "primary-container": "#0a2342",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#44474e",
        "on-primary-fixed-variant": "#324768",
        "error": "#ba1a1a",
        "surface-container-high": "#dee8ff",
        "primary": "#000d22",
        "on-primary-fixed": "#021c3a",
      },
      // Note: Removed the fontFamily conflict entirely. 
      // It will now use the browser's default sans unless you import Inter in your layout.
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      spacing: {
        "gutter": "24px",
      }
    },
  },
  plugins: [],
};
export default config;